export const PARAM = Object.freeze({
  PADDLE_WIDTH: 0,
  PADDLE_HEIGHT: 1,
  PADDLE_SPEED: 2,
  BALL_RADIUS: 3,
  BALL_SPEED: 4,
  BOUNCE_ZONE_0: 5,
  BOUNCE_ZONE_1: 6,
  BOUNCE_ZONE_2: 7,
  BOUNCE_ZONE_3: 8,
  BOUNCE_ZONE_4: 9,
  BOUNCE_ZONE_5: 10,
  BOUNCE_ZONE_6: 11,
  BOUNCE_ZONE_7: 12,
});

export const controls = [
  {
    label: "Paddle Width",
    paramId: PARAM.PADDLE_WIDTH,
    min: 20,
    max: 720,
    step: 1,
    decimals: 1,
  },
  {
    label: "Paddle Height",
    paramId: PARAM.PADDLE_HEIGHT,
    min: 6,
    max: 80,
    step: 1,
    decimals: 1,
  },
  {
    label: "Paddle Speed",
    paramId: PARAM.PADDLE_SPEED,
    min: 50,
    max: 1200,
    step: 1,
    decimals: 1,
  },
  {
    label: "Ball Radius",
    paramId: PARAM.BALL_RADIUS,
    min: 2,
    max: 30,
    step: 0.5,
    decimals: 2,
  },
  {
    label: "Ball Speed",
    paramId: PARAM.BALL_SPEED,
    min: 50,
    max: 2000,
    step: 1,
    decimals: 1,
  },
  {
    label: "Bounce Zone 0 Angle",
    paramId: PARAM.BOUNCE_ZONE_0,
    min: 5,
    max: 85,
    step: 1,
    decimals: 1,
  },
  {
    label: "Bounce Zone 1 Angle",
    paramId: PARAM.BOUNCE_ZONE_1,
    min: 5,
    max: 85,
    step: 1,
    decimals: 1,
  },
  {
    label: "Bounce Zone 2 Angle",
    paramId: PARAM.BOUNCE_ZONE_2,
    min: 5,
    max: 85,
    step: 1,
    decimals: 1,
  },
  {
    label: "Bounce Zone 3 Angle",
    paramId: PARAM.BOUNCE_ZONE_3,
    min: 5,
    max: 85,
    step: 1,
    decimals: 1,
  },
  {
    label: "Bounce Zone 4 Angle",
    paramId: PARAM.BOUNCE_ZONE_4,
    min: 5,
    max: 85,
    step: 1,
    decimals: 1,
  },
  {
    label: "Bounce Zone 5 Angle",
    paramId: PARAM.BOUNCE_ZONE_5,
    min: 5,
    max: 85,
    step: 1,
    decimals: 1,
  },
  {
    label: "Bounce Zone 6 Angle",
    paramId: PARAM.BOUNCE_ZONE_6,
    min: 5,
    max: 85,
    step: 1,
    decimals: 1,
  },
  {
    label: "Bounce Zone 7 Angle",
    paramId: PARAM.BOUNCE_ZONE_7,
    min: 5,
    max: 85,
    step: 1,
    decimals: 1,
  },
];
